# Generated by Django 5.2.7 on 2025-11-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='monto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multa',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
