# Generated by Django 5.2.7 on 2025-11-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multa', '0002_multa_monto_alter_multa_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='nombre',
            field=models.CharField(blank=True, null=True),
        ),
    ]
