# Generated by Django 5.2.7 on 2025-11-04 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestamo', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('autor', models.CharField()),
                ('titulo', models.CharField(max_length=30)),
                ('estado', models.BooleanField()),
                ('id_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.prestamo')),
                ('numero_socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
