# Generated by Django 5.2.7 on 2025-11-04 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
        ('prestamo', '0001_initial'),
        ('usuario', '0002_alter_usuario_id_multa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='id_prestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamo.prestamo'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='numero_socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
