# Generated by Django 5.2.7 on 2025-11-04 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('numero_socio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('id_multa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multa.multa')),
            ],
        ),
    ]
